# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('north', models.DecimalField(decimal_places=6, max_digits=9)),
                ('south', models.DecimalField(decimal_places=6, max_digits=9)),
                ('east', models.DecimalField(decimal_places=6, max_digits=9)),
                ('west', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
